# Generated by Django 3.0.3 on 2020-07-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20200720_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
